meta:
  student: B25MT024
  attempt_id: aab8deac-8a2c-4bae-98c3-86c5564658b5
  timestamp: '2026-02-17 18:20:51.181905+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
