meta:
  student: B25MM015
  attempt_id: 3e843aa7-f638-440c-a515-f00e454ef96d
  timestamp: '2026-02-17 18:20:48.800875+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
