meta:
  student: B25ME023
  attempt_id: 48534982-4017-4907-887d-ec9e53958eea
  timestamp: '2026-02-17 18:20:45.416321+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
