meta:
  student: B25CS015
  attempt_id: 1a69767c-f61c-49b0-b2bf-ab153a9d2ff5
  timestamp: '2026-02-17 18:20:29.960659+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
