meta:
  student: B25EC019
  attempt_id: 757ac30c-884f-4a0b-86c1-e9995bc7e74f
  timestamp: '2026-02-17 18:20:37.863745+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
