meta:
  student: student_crash
  attempt_id: 6b4e64f8-19a5-44de-83a9-2095bb930aae
  timestamp: '2026-02-17 06:23:26.984250+00:00'
  status: success
  language: python
question_config:
  timeout: 2
  language: python
  entry_point: solution
  execution_mode:
    type: function
    entry_point: solution
