meta:
  student: B25CS042
  attempt_id: 57665bf0-b4c5-4c35-b3ad-6b7e8958f19a
  timestamp: '2026-02-17 18:20:30.161868+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
