meta:
  student: B25CS010
  attempt_id: 4549a1aa-9be5-4732-bc17-8cfba8cda7d4
  timestamp: '2026-02-17 17:39:28.757771+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
