meta:
  student: B25ME012
  attempt_id: 09a8c843-27ad-4cd9-afd9-75c1572012f7
  timestamp: '2026-02-17 18:20:44.671971+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
