meta:
  student: B25ME021
  attempt_id: 3668976b-8907-4bb8-997d-738d773e4d0d
  timestamp: '2026-02-17 18:20:45.225417+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
