meta:
  student: B25MT030
  attempt_id: a2406bd3-54c5-4dae-98c5-beee233289fc
  timestamp: '2026-02-17 18:20:51.409640+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
