meta:
  student: S25MA013
  attempt_id: ef411848-3a56-4a0b-8e61-1bc79a19f7a4
  timestamp: '2026-02-17 18:20:52.032078+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
