meta:
  student: B25CS018
  attempt_id: f3dab7af-72a9-4e4d-8c6f-a6de5dd7d5a0
  timestamp: '2026-02-17 17:39:28.760136+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
