meta:
  student: B25DS042
  attempt_id: 437e72f6-1fa6-402e-811d-ec4a5ca606a0
  timestamp: '2026-02-17 18:20:36.445785+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
