meta:
  student: B25EE026
  attempt_id: a6c2a0c6-344f-446d-b390-85eed43ca506
  timestamp: '2026-02-17 18:20:41.668240+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
