title: Find the Missing Number
slug: find-the-missing-number-344756e3
entry_point: findMissingNumber
execution:
  timeout_seconds: 2
  memory_limit_mb: 128
  language: python
test_cases:
- input: '[3, 0, 1]'
  expected_output: '2'
  explanation: n = 3, so the array should contain numbers from 0 to 3.  The missing
    number is 2.
  concept: 'Concept / Tag: Arrays, Math, Bit Manipulation'
  is_hidden: false
  points: 10
