meta:
  student: B25DS034
  attempt_id: 4d4ad5bc-caee-4288-bbc6-707e3e8229a3
  timestamp: '2026-02-17 18:20:35.868319+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
