meta:
  student: B25EC045
  attempt_id: 801e636e-9b0c-4a86-83de-25fad8f28240
  timestamp: '2026-02-17 18:20:39.551903+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
