meta:
  student: B25EC006
  attempt_id: d5479c8c-2f1d-4f97-8a0e-943b4415173f
  timestamp: '2026-02-17 18:20:36.940596+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
