meta:
  student: B25EE012
  attempt_id: 4709c663-4da2-49c4-b70a-f538f12ae517
  timestamp: '2026-02-17 18:20:40.453601+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
