meta:
  student: B25ME009
  attempt_id: 5cce6773-0e34-42ca-bc59-9cfee6f4ede5
  timestamp: '2026-02-17 18:20:44.576863+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
