title: Sum of Even Numbers in a List
slug: sum-of-even-numbers-in-a-list-1d2b7914
entry_point: sum_even_numbers
execution:
  timeout_seconds: 2
  memory_limit_mb: 128
  language: python
test_cases:
- input: '[1, 2, 3, 4, 5, 6]

    '
  expected_output: '12

    '
  explanation: "Even numbers are 2, 4, 6 \u2192 Sum = 12"
  concept: General Case
  is_hidden: false
  points: 10
- input: '[7, 9, 11]

    '
  expected_output: '0'
  explanation: There are no even numbers.
  concept: Special Case
  is_hidden: false
  points: 10
