meta:
  student: B25DS015
  attempt_id: 92dce33d-1384-42be-a1d1-bb06a8faba0f
  timestamp: '2026-02-17 18:20:34.485270+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
