meta:
  student: B25EE001
  attempt_id: 2221043b-b0cb-4cc5-9a61-06f53eb63a56
  timestamp: '2026-02-17 18:20:39.718786+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
