meta:
  student: B25ME035
  attempt_id: 5886b43e-b6b3-4890-a28e-b9576c74612a
  timestamp: '2026-02-17 18:20:46.345223+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
