meta:
  student: B25MT023
  attempt_id: 9fc816a6-c63e-4650-bd20-b7cc4297bcf8
  timestamp: '2026-02-17 18:20:51.155925+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
