meta:
  student: B25DS035
  attempt_id: 20ca161c-bf1f-423f-a741-6e775f28ae4e
  timestamp: '2026-02-17 18:20:35.872496+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
