meta:
  student: B25ME030
  attempt_id: 2d08e302-b9f3-47cf-a620-b51f1a6d9f53
  timestamp: '2026-02-17 18:20:45.856020+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
