meta:
  student: B25MT027
  attempt_id: b76f67c6-374f-4941-a447-198ad0cba9c5
  timestamp: '2026-02-17 18:20:51.228976+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
