meta:
  student: B25MM014
  attempt_id: 441c6263-69af-493d-895c-be2fae26ef12
  timestamp: '2026-02-17 18:20:49.568764+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
