meta:
  student: B25ME031
  attempt_id: 24d1714c-16d0-4a3d-8669-ad0ea361bdee
  timestamp: '2026-02-17 18:20:45.894189+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
