meta:
  student: B25DS008
  attempt_id: de1cdea3-fea4-4a24-9d45-8562938c0b3a
  timestamp: '2026-02-17 18:20:34.083307+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
