meta:
  student: B25MM002
  attempt_id: 53b6919e-8849-4994-af01-6ee92b3a9f00
  timestamp: '2026-02-17 18:20:48.312587+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
