meta:
  student: B25ME008
  attempt_id: 439d2792-0da7-4a01-ac17-ce4e47715863
  timestamp: '2026-02-17 18:20:44.500625+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
