meta:
  student: B25EC032
  attempt_id: 97229a23-c591-446c-9a4e-16fb835fa345
  timestamp: '2026-02-17 18:20:38.799770+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
