meta:
  student: B25MM011
  attempt_id: 1b4dabc3-2bc4-4165-89cd-3dc22547467d
  timestamp: '2026-02-17 18:20:48.650125+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
