meta:
  student: B25ME016
  attempt_id: 936667c9-ee40-4ed4-8afb-b7543935368c
  timestamp: '2026-02-17 18:20:44.948591+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
