meta:
  student: B25EE056
  attempt_id: 3ed23d25-e5b1-42b0-9022-56f5805aeb7e
  timestamp: '2026-02-17 18:20:43.422000+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
