meta:
  student: student_input_test
  attempt_id: 78c4a57c-4bed-4399-9600-0a4c9b614fda
  timestamp: '2026-02-17 06:43:24.774958+00:00'
  status: success
  language: python
question_config:
  timeout: 2
  language: python
  entry_point: sum_even_numbers
