meta:
  student: student_crash
  attempt_id: 3ed440af-d04d-4c20-92ed-943981757843
  timestamp: '2026-02-17 06:29:33.486472+00:00'
  status: success
  language: python
question_config:
  timeout: 2
  language: python
  entry_point: solution
