meta:
  student: B25ME041
  attempt_id: 14bb57d7-9edf-40cc-90fb-4799f734a08b
  timestamp: '2026-02-17 18:20:46.690011+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
