meta:
  student: B25MT019
  attempt_id: ab99f0a0-6398-46dc-ab67-5d93086a67f3
  timestamp: '2026-02-17 18:20:50.775213+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
