title: Valid Bracket Sequence
slug: valid-bracket-sequence-cf25c061
entry_point: isValidBracketSequence
execution:
  timeout_seconds: 2
  memory_limit_mb: 128
  language: python
test_cases:
- input: '"()[]{}"'
  expected_output: 'true'
  explanation: Every opening bracket is matched correctly with its corresponding closing
    bracket in the right order.
  concept: Stack, String Manipulation
  is_hidden: false
  points: 10
- input: '"(]"'
  expected_output: 'false'
  explanation: The opening parenthesis '(' is incorrectly closed by a square bracket
    ']'.
  concept: Stack, Logic Validation
  is_hidden: false
  points: 10
