meta:
  student: B25MM027
  attempt_id: 119525d5-b4b7-45a9-9adf-5add5badc99f
  timestamp: '2026-02-17 18:20:49.418380+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
