meta:
  student: B25MM026
  attempt_id: 79af1c36-834d-48a1-bd12-b8349618e974
  timestamp: '2026-02-17 18:20:49.351468+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
