meta:
  student: B25EE046
  attempt_id: 7b92ed4c-4b0e-4547-aacb-2405c0b4bb5d
  timestamp: '2026-02-17 18:20:42.803427+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
