meta:
  student: student_crash
  attempt_id: 522161e0-51b9-4454-aa95-4815b47e6ec3
  timestamp: '2026-02-17 06:26:32.221374+00:00'
  status: success
  language: python
question_config:
  timeout: 2
  language: python
  entry_point: solution
  execution_mode:
    type: function
    entry_point: solution
