meta:
  student: B25EC011
  attempt_id: dce8966c-1b93-4b38-a13f-8c919186edb7
  timestamp: '2026-02-17 18:20:37.449085+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
