meta:
  student: B25DS037
  attempt_id: 4271ed60-4caf-4c73-84d2-054a10011077
  timestamp: '2026-02-17 18:20:36.085251+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
