meta:
  student: B25EC028
  attempt_id: ea6a5111-16c4-429d-af00-08bb7cd01c11
  timestamp: '2026-02-17 18:20:38.467159+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
