meta:
  student: B25EE002
  attempt_id: 5c54d4a9-ff62-4be7-a18f-44e9838cb3f5
  timestamp: '2026-02-17 18:20:39.827334+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
