meta:
  student: B25MT015
  attempt_id: 355e8d80-4056-450d-b7b4-f7748d6c9c2d
  timestamp: '2026-02-17 18:20:52.758097+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
