meta:
  student: B25EC039
  attempt_id: 8b182112-abba-47af-a8d6-00d1e86856be
  timestamp: '2026-02-17 18:20:39.251035+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
