meta:
  student: B25CS059
  attempt_id: 0d41d362-c79b-4f5b-b968-fb764c6e3070
  timestamp: '2026-02-17 18:20:33.542790+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
