meta:
  student: B25CS014
  attempt_id: 25f6c370-b716-4924-9f27-ac9f33cbe3e3
  timestamp: '2026-02-17 17:39:28.784125+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
