meta:
  student: B25EE009
  attempt_id: b5b4a3ae-850f-4cf8-b095-95e829725ed3
  timestamp: '2026-02-17 18:20:40.403128+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
