meta:
  student: B25MM007
  attempt_id: d712a74b-2476-4d97-b585-6475ec41c309
  timestamp: '2026-02-17 18:20:48.421875+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
