meta:
  student: B25EE031
  attempt_id: dbcd320d-464b-4dd6-b93f-8131a34b2d5d
  timestamp: '2026-02-19 13:53:15.033540+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: reverse_string
