meta:
  student: B25EE011
  attempt_id: 4e5ab80d-4213-4bc5-8e54-3a6c14268cca
  timestamp: '2026-02-17 18:20:40.417242+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
