meta:
  student: B25CS028
  attempt_id: 50a7ef2b-7b14-47d8-8ff3-3a3b050f6ad4
  timestamp: '2026-02-17 18:20:30.106874+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
