meta:
  student: B25DS003
  attempt_id: c70ee699-985d-46d1-b062-19845321d1c5
  timestamp: '2026-02-17 18:20:33.887877+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
