meta:
  student: B25DS016
  attempt_id: 6365759a-a0ea-43b6-9b29-f78d497ed0d6
  timestamp: '2026-02-17 18:20:34.502453+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
