meta:
  student: B25ME039
  attempt_id: 08391274-91d1-4fd0-8c5d-e0c7f78814da
  timestamp: '2026-02-17 18:20:46.560357+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
