meta:
  student: B25EE024
  attempt_id: 55472f64-816d-400d-9ef4-3eb55c42563a
  timestamp: '2026-02-17 18:20:41.433355+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
