meta:
  student: B25EC034
  attempt_id: 64f30d9f-371f-4a0e-b805-d21692190a0f
  timestamp: '2026-02-17 18:20:38.829699+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
