meta:
  student: B25CS036
  attempt_id: c2b21153-6dbd-427d-a339-9b6da24b346e
  timestamp: '2026-02-17 18:20:30.249703+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
