meta:
  student: B25MT025
  attempt_id: 681d70d1-dbaf-4bc3-b408-c23552cb3292
  timestamp: '2026-02-17 18:20:51.204446+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
