meta:
  student: B25ME006
  attempt_id: 038a384c-c01e-4c15-9eb5-12299755bf1b
  timestamp: '2026-02-17 18:20:44.414295+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
