title: Count Vowels in a String
slug: count-vowels-in-a-string-4b083527
entry_point: count_vowels
execution:
  timeout_seconds: 2
  memory_limit_mb: 128
  language: python
test_cases:
- input: '"Hello World"

    '
  expected_output: '3

    '
  explanation: "Vowels are e, o, o \u2192 Total = 3"
  concept: General Case
  is_hidden: false
  points: 10
- input: '"CSL100"

    '
  expected_output: '0'
  explanation: No vowels are present.
  concept: Edge Case
  is_hidden: false
  points: 10
