meta:
  student: S25MA001
  attempt_id: e3753689-6869-4cf0-86e1-0caaec66822b
  timestamp: '2026-02-17 18:20:51.706101+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
