meta:
  student: S25MA014
  attempt_id: 24e9c9c4-7b0f-405a-8ebc-d69bd771d67d
  timestamp: '2026-02-17 18:20:52.131825+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
