meta:
  student: B25MT026
  attempt_id: 412be522-fb79-4c29-9e18-93bd193813fc
  timestamp: '2026-02-17 18:20:51.229598+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
