meta:
  student: B25EE059
  attempt_id: 891dddd9-2d08-4d28-82d4-e2f4bb1a43ec
  timestamp: '2026-02-17 18:20:43.593255+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
