meta:
  student: B25EC024
  attempt_id: 6faa717e-f640-4799-b1b4-5645933213a0
  timestamp: '2026-02-17 18:20:38.335948+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
