meta:
  student: B25ME060
  attempt_id: 6b5fbb0f-14d3-434d-98fc-1d5722efc9e9
  timestamp: '2026-02-17 18:20:48.010050+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
