meta:
  student: B25CS033
  attempt_id: f568b25a-8aee-4571-ad37-3a6b65d3a6f4
  timestamp: '2026-02-17 18:20:30.175169+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
