meta:
  student: B25ME024
  attempt_id: a2515d1f-8789-4822-a3cc-dc34b0000d33
  timestamp: '2026-02-17 18:20:45.451695+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
