meta:
  student: B25DS033
  attempt_id: ed1b4fb5-4aca-49b1-bb24-80a42fa36b90
  timestamp: '2026-02-17 18:20:35.869309+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
