meta:
  student: B25CS013
  attempt_id: 8820202b-d175-4271-b585-c1bb693b7c4c
  timestamp: '2026-02-17 18:20:29.971935+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
