meta:
  student: B25DS021
  attempt_id: bed89bc4-61cd-4a00-8cda-77da6bbb4d20
  timestamp: '2026-02-17 18:20:34.848600+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
