meta:
  student: B25ME025
  attempt_id: dc5ca4d6-cb69-4849-9905-6c2279ec5d88
  timestamp: '2026-02-17 18:20:45.487653+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
