meta:
  student: B25EE031
  attempt_id: ce1178d7-856b-46ee-bed1-90fa94273522
  timestamp: '2026-02-19 14:01:02.101897+00:00'
  status: fail
  language: python
question_config:
  timeout: 2
  language: python
  entry_point: reverse_string
  execution_mode:
    type: function
