meta:
  student: B25MT017
  attempt_id: a68a46b5-bf57-4c20-af80-6ab6009fbfea
  timestamp: '2026-02-17 18:20:50.591085+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
