meta:
  student: B25ME017
  attempt_id: d5189fa7-236b-4d90-9a3b-a510fde5c812
  timestamp: '2026-02-17 18:20:44.958351+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
