meta:
  student: B25CS005
  attempt_id: 01642e1e-082c-4a8c-94b0-4c0efcebabe6
  timestamp: '2026-02-17 17:39:28.785666+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
