meta:
  student: B25ME004
  attempt_id: ab385e99-ab33-41d6-ad47-250529c9131e
  timestamp: '2026-02-17 18:20:44.149934+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
