meta:
  student: B25CS009
  attempt_id: 8a5a89bb-1aff-4cd6-b3e8-27e3297e758c
  timestamp: '2026-02-17 17:39:28.771899+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
