meta:
  student: student_robust_test
  attempt_id: b4f79522-c8c9-461d-b959-569e6aa63f0c
  timestamp: '2026-02-17 07:18:14.849134+00:00'
  status: success
  language: python
question_config:
  timeout: 2
  language: python
  entry_point: reverse_array
