meta:
  student: B25MM025
  attempt_id: 80295e8a-0c2c-4ad1-9b7e-613cfefe35e7
  timestamp: '2026-02-17 18:20:49.145729+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
