meta:
  student: B25EE014
  attempt_id: 41281361-19b8-4ba8-9765-ccc9258b202f
  timestamp: '2026-02-17 18:20:40.746662+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
