meta:
  student: B25ME019
  attempt_id: 54343495-0654-43bd-a274-e076f8fd55fc
  timestamp: '2026-02-17 18:20:45.190897+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
