meta:
  student: B25EE043
  attempt_id: ff14ef70-e3a8-47be-a862-9212eb4ef281
  timestamp: '2026-02-17 18:20:42.658149+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
