meta:
  student: B25DS009
  attempt_id: 2df88824-6110-4c27-b652-9467f7a87ddf
  timestamp: '2026-02-17 18:20:34.105277+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
