meta:
  student: B25DS011
  attempt_id: 32b1d373-a749-4aaa-8a04-47c862f6c681
  timestamp: '2026-02-17 18:20:34.323393+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
