meta:
  student: B25ME043
  attempt_id: 21ae3b4a-ddb8-4ca6-9e40-549256fc921e
  timestamp: '2026-02-17 18:20:46.779137+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
