meta:
  student: B25ME055
  attempt_id: 1fb115d3-2711-4c25-8884-92cb630f8fd0
  timestamp: '2026-02-17 18:20:47.613931+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
