meta:
  student: B25EE013
  attempt_id: 4563df50-3748-406a-aeab-a6f5b5344a79
  timestamp: '2026-02-17 18:20:40.522263+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
