meta:
  student: B25ME045
  attempt_id: af0278fc-75bd-44b4-800b-bbc2217e60d9
  timestamp: '2026-02-17 18:20:46.883653+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
