meta:
  student: B25CS054
  attempt_id: 2f60f7b3-a535-4c53-a2b8-e3dc91d7015b
  timestamp: '2026-02-17 18:20:33.408449+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
