meta:
  student: B25MT002
  attempt_id: 716457d3-1e34-46a2-9c49-a195ed26a230
  timestamp: '2026-02-17 18:20:49.707807+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
