meta:
  student: B25ME051
  attempt_id: ed13e133-5a55-431a-8ca6-92280df8a773
  timestamp: '2026-02-17 18:20:47.455700+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
