meta:
  student: B25EE006
  attempt_id: cdeafc3f-e51c-4d36-ae83-a9cffbf7eece
  timestamp: '2026-02-17 18:20:40.232706+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
