meta:
  student: S25MA018
  attempt_id: bf41fbc7-d87c-4bf2-b384-11f34c2c19c4
  timestamp: '2026-02-17 18:20:52.745165+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
