meta:
  student: B25MM005
  attempt_id: 3b35a9d0-cbcf-470f-a39c-0666f137cb8b
  timestamp: '2026-02-17 18:20:52.724357+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
