meta:
  student: B25DS006
  attempt_id: 0486e607-ddc3-4222-9e7f-7e1627eca471
  timestamp: '2026-02-17 18:20:34.010248+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
