meta:
  student: B25EE050
  attempt_id: e95381b1-8d52-428f-9b92-3222743ffa04
  timestamp: '2026-02-17 18:20:43.032645+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
