meta:
  student: B25DS004
  attempt_id: 61c36fd4-4586-4e94-8036-35dda6ccc038
  timestamp: '2026-02-17 18:20:33.961860+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
