meta:
  student: B25MT021
  attempt_id: 291e5a2b-d2ba-492a-9474-c63ef29c89ee
  timestamp: '2026-02-17 18:20:50.901912+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
