meta:
  student: B25DS007
  attempt_id: db99badc-e3ad-44a7-a6b9-84fb0bc064ce
  timestamp: '2026-02-17 18:20:34.030226+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
