meta:
  student: B25CS014
  attempt_id: 80cb1aad-9620-4e37-ba44-829fca4f0bf8
  timestamp: '2026-02-17 18:20:29.971465+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
