meta:
  student: B25MM016
  attempt_id: 910f279e-ab77-4afc-ba41-9b84255ec6fc
  timestamp: '2026-02-17 18:20:48.923700+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
