meta:
  student: B25DS030
  attempt_id: 63335758-e1ce-4616-ae17-55f660e2cb1b
  timestamp: '2026-02-17 18:20:35.629161+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
