meta:
  student: S25MA015
  attempt_id: 3367dca8-a2f1-4632-99eb-33be43788888
  timestamp: '2026-02-17 18:20:52.137728+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
