meta:
  student: B25EE005
  attempt_id: 15770df5-3521-4e97-802a-99879b9ccbd2
  timestamp: '2026-02-17 18:20:40.137749+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
