meta:
  student: S25MA017
  attempt_id: 671cf487-b357-4ac6-9a78-4f1c6ca0f7a1
  timestamp: '2026-02-17 18:20:52.350874+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
