meta:
  student: B25ME018
  attempt_id: b2b1b3c9-90d8-4050-b1ed-c4dc780cc767
  timestamp: '2026-02-17 18:20:45.187112+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
