meta:
  student: B25ME052
  attempt_id: 5b436acd-ccd7-45b2-a979-9b914f80b972
  timestamp: '2026-02-17 18:20:47.564598+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
