meta:
  student: B25EC023
  attempt_id: 268a5ab5-f6e3-4865-8980-45c7721fde70
  timestamp: '2026-02-17 18:20:38.303423+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
