meta:
  student: B25CS002
  attempt_id: b26e07dc-92b1-4b89-87fb-a94e85de27ea
  timestamp: '2026-02-17 18:20:29.844406+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
