meta:
  student: B25CS022
  attempt_id: b7089b9d-5660-4e3b-aa40-cd0776f98ae8
  timestamp: '2026-02-17 18:20:30.118427+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
