meta:
  student: B25EE007
  attempt_id: 9558a603-b982-4889-8718-986f907cbc17
  timestamp: '2026-02-17 18:20:40.268726+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
