meta:
  student: B25CS031
  attempt_id: efd6182f-aa3c-4048-b892-9d8d23f3c6b2
  timestamp: '2026-02-17 18:20:30.252634+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
