meta:
  student: B25MM012
  attempt_id: 87ac3354-bc5d-4a26-bf21-ddfa490afe39
  timestamp: '2026-02-17 18:20:48.789081+00:00'
  status: fail
  language: python
question_config:
  memory: 128
  timeout: 2
  entry_point: sum_even_numbers
